### ISSUE TITLE
Unable to parse time "1 Jan, 2023 @ 12:19pm", please report this.

### ISSUE THREAD

**Issue by rts7** [Ryzhehvost/BoosterCreator#17]
I got this today, I assume because of the year change.

**Comment by Ryzhehvost** [comment]
Thank you for report, I will look into it

**Comment by Ryzhehvost** [comment]
I made changes that should fix this issue, but don't have time to check. If you are willing to help - please, update to pre-release https://github.com/Ryzhehvost/BoosterCreator/releases/tag/1.2.4.0 and check if it works without errors.

**Comment by rts7** [comment]
Thanks for your help, but it didn't work. I still get the same message but the planning date is also weird now and it seems to be in a different format. (I don't remember how it were before though).

2022-12-31 15:24:06|dotnet-6708|INFO|x|CreateBooster() Unable to parse time "1 Jan, 2023 @ 12:19pm", please report this.
2022-12-31 15:24:06|dotnet-6708|INFO|x|CreateBooster() <x> Crafting booster from xxx is not available now
2022-12-31 15:24:06|dotnet-6708|INFO|x|CreateBooster() <x> Next attempt to make booster from xxx is planned at 12/31/2022 11:24 PM

**Comment by rts7** [comment]
Now that I think about it, I think it was probably the same before and you can disregard my comment. Also, maybe we should wait until tomorrow because it is possible that the problem occurs exactly and only today because of the planning for tomorrow. It might work without any changes tomorrow.

**Comment by rts7** [comment]
Happy new year! It works today both with the old version and the pre-release one. I guess something goes wrong when it tries to schedule for the next year but it is a non-issue in practice.

**Comment by Ryzhehvost** [comment]
It has nothing to do with year per se, it's just the date format. "1 Jan, 2023 @ 12:19pm" has a comma after month, previously I haven't seen such format in steam, so plugin was unable to parse it. I've changed parsing algorithm to include this comma, but you said it did not help, so it needs more testing. If it works now it means either you didn't hit it yet (it only parses the date when specified booster can't be crafted - in this case steam reports when it will be available), or that steam somehow returns now different date format.

**Comment by rts7** [comment]
I am not 100% sure I understand all of your post but I certainly crafted a booster that yesterday was giving me an error and there is no error for tomorrow. Maybe steam gives the weird format only when scheduling for the following year.

**Comment by Ryzhehvost** [comment]
> Maybe steam gives the weird format only when scheduling for the following year.

Yes, that may be an issue. You never know what to expect from steam...

**Comment by Ryzhehvost** [comment]
> Actually, didn't you forget to mention the year? Maybe that issue with your fix is just that.

Omg, you are right! I totally missed it. Thank you!

**Comment by woctezuma** [comment]
Maybe also include the other case:

```
"MMM d, yyyy @ h:mmtt"
```

**Comment by Ryzhehvost** [comment]
Yes, it won't hurt to add.

**Comment by Ryzhehvost** [comment]
Ok, I added the year to format string, hopefully it will be enough, but we will only see it next year. Since @rts7 confirmed that previous pre-release works, I marked new release as stable. Going to close this issue for now, if next year it will appear again - please open a new issue. @woctezuma, thanks a lot for your help!
